---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    username: root2
    password:

environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost:3306/tempvs?useSSL=false
    test:
        dataSource:
            dbCreate: create-drop
            url: jdbc:mysql://localhost:3306/test_tempvs?autoreconnect=true;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost:3306/tempvs?autoreconnect=true;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
---
grails:
    profile: web
    codegen:
        defaultPackage: tempvs
    spring:
        transactionManagement:
            proxies: false
    plugin:
        springsecurity:
            securityConfigType: InterceptUrlMap
            userLookup:
                userDomainClassName: com.tempvs.user.User
                usernamePropertyName: email
                passwordPropertyName: password
                authorityJoinClassName: com.tempvs.user.UserRole
            auth:
                loginFormUrl: /auth/index
            failureHandler:
                defaultFailureUrl: /auth/index
            successHandler:
                defaultTargetUrl: /user/show
            authority:
                className: com.tempvs.user.Role
            requestMap:
                className: com.tempvs.user.Requestmap
            interceptUrlMap:
                - pattern: /auth/**
                  access:
                      - permitAll
                - pattern: /user/verify/**
                  access:
                      - permitAll
                - pattern: /user/register
                  access:
                      - permitAll
                - pattern: /user/createUser/**
                  access:
                      - permitAll
                - pattern: /user/show/**
                  access:
                      - permitAll
                - pattern: /user/getAvatar
                  access:
                      - permitAll
                - pattern: /assets/**
                  access:
                      - permitAll
                - pattern: /**/js/**
                  access:
                      - permitAll
                - pattern: /**/css/**
                  access:
                      - permitAll
                - pattern: /**/images/**
                  access:
                      - permitAll
                - pattern: /**/favicon.ico
                  access:
                      - permitAll
                - pattern: /**
                  access:
                      - isAuthenticated()
#            filterChain:
#                chainMap:
#                    - pattern: /assets*//**//**
#                      filters: none
#                    - pattern: *//**//**//**//*js*//**//**
#                      filters: none
#                    - pattern: *//**//**//**//*css*//**//**
#                      filters: none
#                    - pattern: *//**//**//**//*images*//**//**
#                      filters: none
#                    - pattern: *//**//**//**//*favicon.ico
#                      filters: none
#                    - pattern: *//**//**
#                      filters: JOINED_FILTERS
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    mail:
        host: smtp.gmail.com
        port: 587
        username: tempvs.com@gmail.com
        password: tempvs.com.pwd
        props:
            mail.smtp.port: 587
            mail.smtp.starttls.enable: true

endpoints:
    jmx:
        unique-names: true
